### ISSUE TITLE
[iOS] header image 확대되어 보임

### ISSUE THREAD

**Issue by nypark425** [nypark425/staywithjoy.github.io#6]
- 모바일 > IOS > header image가 확대되어 보임
- 'background-attachment: fixed'가 적용되지 않고, scroll됨.
- 아래 스크린샷 참고

![kakaotalk_photo_2018-01-29-00-17-48_40](https://user-images.githubusercontent.com/10542786/35483831-fd60ca82-0489-11e8-9e47-217a57b54cf5.jpeg)

**Comment by nypark425** [comment]
Stack Overlflow 참고 : https://stackoverflow.com/questions/18429620/css-background-size-cover-replacement-for-mobile-safari

**Comment by nypark425** [comment]
1차 시도 -> 실패 :(
```css
  &-image {
    background: url('/assets/image/header-mobile.jpeg') no-repeat center center fixed;
    -webkit-background-size: cover;
    -moz-background-size: cover;
    -o-background-size: cover;
    background-size: cover;
    height: 800px;
    top: 0;
    left: 0;

    /* Preserve aspet ratio */
    min-width: 100%;
    min-height: 100%;
  }
```

**Comment by nypark425** [comment]
2차 시도 -> 성공! 하지만 이미지 함께 스크롤됨.
```css
  &-image {
    background: url('/assets/image/header-mobile.jpeg') no-repeat center center scroll;
    -webkit-background-size: cover;
    -moz-background-size: cover;
    -o-background-size: cover;
    background-size: cover;
    height: 800px;
  }
```
